// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0II-pJJsz9NIrZeSxRj9XhX2pqNKO4BA',
    appId: '1:274193252919:web:43f11d94bd3a6e5e0475b2',
    messagingSenderId: '274193252919',
    projectId: 'yuki-project-4f19a',
    authDomain: 'yuki-project-4f19a.firebaseapp.com',
    storageBucket: 'yuki-project-4f19a.appspot.com',
    measurementId: 'G-038GEJ9NJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5g0oI-S65eRpw_qBmVpn-WZ1_JA2phx0',
    appId: '1:274193252919:android:1e7eed75ba0b09dc0475b2',
    messagingSenderId: '274193252919',
    projectId: 'yuki-project-4f19a',
    storageBucket: 'yuki-project-4f19a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtjCfdlqWNKVkkmGSUQ6yS7IKoea4E0PU',
    appId: '1:274193252919:ios:b507ff65ac2e86b70475b2',
    messagingSenderId: '274193252919',
    projectId: 'yuki-project-4f19a',
    storageBucket: 'yuki-project-4f19a.appspot.com',
    iosClientId: '274193252919-v51g4t0j29r23ojbm11h155b1ueootr7.apps.googleusercontent.com',
    iosBundleId: 'dev.yukiproject.yukiproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtjCfdlqWNKVkkmGSUQ6yS7IKoea4E0PU',
    appId: '1:274193252919:ios:b507ff65ac2e86b70475b2',
    messagingSenderId: '274193252919',
    projectId: 'yuki-project-4f19a',
    storageBucket: 'yuki-project-4f19a.appspot.com',
    iosClientId: '274193252919-v51g4t0j29r23ojbm11h155b1ueootr7.apps.googleusercontent.com',
    iosBundleId: 'dev.yukiproject.yukiproject',
  );
}
